### ISSUE TITLE
Failing in remote docker container

### ISSUE THREAD

**Issue by markedwards** [microsoft/vscode-flake8#133]
This extension is failing for me in a remote docker container.  This is what is shown in the `flake8` output:
```
2023-03-16 10:28:41.759 [info] Error: Client is not running and can't be stopped. It's current state is: starting
	at D.shutdown (/home/gidev/.vscode-server/extensions/ms-python.flake8-2023.4.0/dist/extension.js:1:134381)
	at D.stop (/home/gidev/.vscode-server/extensions/ms-python.flake8-2023.4.0/dist/extension.js:1:133962)
	at D.stop (/home/gidev/.vscode-server/extensions/ms-python.flake8-2023.4.0/dist/extension.js:1:295966)
	at D.handleConnectionError (/home/gidev/.vscode-server/extensions/ms-python.flake8-2023.4.0/dist/extension.js:1:140469)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I would guess this could be a similar issue to [what I encountered with the isort extension](https://github.com/microsoft/vscode-isort/issues/163), but I do not see similar output in the `Remote Extension Host` as with that issue.

Disabling/removing the flake8 extension resolves this issue (the normal flake8 flow still works).  But is the idea to remove that in favor of this new extension?  If so, can we get a `serverEnabled` setting as a workaround?

**Comment by karthiknadig** [comment]
@markedwards For isort we added the `serverless` mode as a stop gap due to a bug in isort itself. We will be removing that mode when the fix is shipped.

the issue here originates from this, in the docker file.
```
RUN ln -s /isortdemo/sitecustomize.py $(python -c 'import site; print(site.getsitepackages()[0])')
```
Basically, it is forcing python to load the `sitecustomize.py` everywhere. I am pretty sure this break debugging as well since debugger relies on DAP over stdout.

Based on the documentation here: https://docs.python.org/3.10/library/site.html . `sitecustomize.py` should get loaded automatically if it is placed in `site-packages`.

you could do the following (might need tweaks) in your docker file:
1. Create a tools venv `python -m venv /isortdemo/.tools-venv`
2. Create a project venv `python -m venv /isortdemo/.venv`
3. Copy the `sitecustomize.py` into `/isortdemo/.venv/libs/site-packages`
4. Set `${workspaceFolder}/.tools-venv/bin/python` as the interpreter for `isort.interpreter : ["${workspaceFolder}/.tools-venv/bin/python"]` and for `flake8.interpreter:  ["${workspaceFolder}/.tools-venv/bin/python"]` .
5. Set the `${workspaceFolder}/.venv/bin/python` as your project interpreter.

your container may not have venv, in that case install  `python3-venv` and `python3-pip` using `apt` or equivalent. `${workspaceFolder}` is a special variable that should get replaced by your actual workspace folder by the extensions.

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
