### ISSUE TITLE
Provide clarity in the docs about pre-existing flake8 settings that should be enabled/disabled after install

### ISSUE THREAD

**Issue by netopsengineer** [microsoft/vscode-flake8#71]
Team,

The extension documentation mentions that the `bundled` version is used, unless there is an existing `python` environment that has `flake8`.  In a situation, where you could have both, would it be pertinent to configure both the `python.linting.flake8enabled: true`, and its associated `args` such that those would be used when not using the `bundled` version, as well as the extensions version of these same settings for when using `bundled`?  Trying to avoid conflicts, and make use of vscode's great in-built capabilities, but also don't want to lose my customizations, or create a `.flake8` file in every project.

**Comment by karthiknadig** [comment]
@netopsengineer The extension uses bundled version or the one in the environment using the same args as configured using `flake8.args` setting. `python.linting.flake8enabled` is the setting for the feature in the `ms-python.python` extension. That feature and setting will be deprecated soon in favor on `ms-python.flake8` extension. The `ms-python.flake8` extension has similar settings as `ms-python.python`, and it extends the capabilities of what was possible with `ms-python.python` extension. You don't have to create a `.flake8` file if you don't want to. You can use the `flake8.args` setting just like you did with python extension.

Added thing you can do in flake8 extension, is that you can choose bundled vs environment flake8 using the `flake8.importStrategy` setting. You can configure any severity, even for flake8 plugins using the `flake8.severity` setting.

**Comment by Apreche** [comment]
@karthiknadig You say the `python.linting.*` settings from the `ms-python.python` extension will be deprecated soon. That's great. But they aren't deprecated yet. In the meantime, we all have two sets of duplicated settings, and it's not clear at all how these settings interact with each other.

If I set `python.linting.flake8enabled` to `false` will that disable the `ms-python.flake8` linter? If it is enabled, will that mean two separate flake8 linters are running simultaneously? If we set `python.linting.flake8args` will the `ms-python.flake8` extension see and respect those settings, or do we have to manually copy them all over to `flake8.args`?

Also, does this extension have any effect on `python.formatting.autopep8`? Is that going to be split into a separate extension as well?

**Comment by karthiknadig** [comment]
## For `ms-python.python` version 2022.16 and earlier:

If you have `python.linting.flake8Enabled` set to true, and you have `ms-python.flake8` extension. Then two instances of flake8 will be running. `python.linting.flake8Enabled` set to false turns of `ms-python.python` 's instance of flake8.

## For `ms-python.python` version 2022.17.*:

This is insider's version where the transition to new behavior happens. See below for new behavior.

## For `ms-python.python` version 2022.18 and later:

If you have `ms-python.flake8` installed, then `ms-python.python` extension will detect that, and turn off `flake8` linting from `ms-python.python` extension. `ms-python.flake8` extension is not affected by the `python.linting.flake8Enabled` setting.  `ms-python.flake8` extension can handle both `flake8.args` and `python.linting.flake8args`, priority goes to `flake8.args`. `pyhton.linting.flake8path` is also honored. The `python.linting.flake8Severity.*` settings are not honored, since we don't see significant usage of those. 

We are doing roll out of the `ns-python.flake8` extension with the current release. Once we see enough usage of the `ms-pyhton.flake8` extension, we will start marking the old settings as deprecated in some future release. That will be left for a few releases on deprecated until users transition over to new settings and extension. Meanwhile, the `ms-python.flake8` extension will continue to honor the `python.linting.flake8args` and `python.linting.flake8path`.

As for `autopep8`, that is available as an extension. We have not started the migration process yet. https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8

**Comment by Apreche** [comment]
Thank you so much, that is very helpful. I greatly approve of this new approach of putting these into extensions. It was very annoying always having to install these tools into each development environment.

**Comment by netopsengineer** [comment]
agreed, thanks @karthiknadig  that was the info I was looking for, because it was not clear what we do in the mean time or what the future would look like.  I also like this extension based approach, and hope that you all continue down this track.
